# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Learn IIIF
description: > # this means to ignore newlines until "baseurl:"
  Learn IIIF, a quick way to get up to speed on IIIF.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.learniiif.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iiif_io
github_username:  IIIF-Commons

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
keep_files:
  - assets/javascripts/bundle.js
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
destination: public
source: src
sass:
  load_paths:
    - _sass
    - node_modules

collections:
  overview:
    output: true
    # permalink: /:collection/:name
  image-api:
    output: true
  presentation_api:
    output: true
